<?php
declare(strict_types=1);
$modules = is_array($modules ?? null) ? $modules : [];
$courseId = (int) ($course['id'] ?? 0);
?>
<div class="mb-4"><a href="<?= e(url('admin/cursos')) ?>">&larr; Cursos</a><h1 class="h3 mt-2">Temario: <?= e((string) ($course['title'] ?? '')) ?></h1></div>
<div class="admin-card card p-4 mb-4"><h2 class="h5">Añadir módulo</h2><form method="post" action="<?= e(url('admin/cursos/' . $courseId . '/modulos')) ?>" class="row g-2 align-items-end"><?= csrf_field() ?><div class="col-md-5"><label class="form-label" for="module-title">Nombre</label><input class="form-control" id="module-title" name="title" required></div><div class="col-md-4"><label class="form-label" for="module-summary">Resumen</label><input class="form-control" id="module-summary" name="summary"></div><div class="col-md-2"><label class="form-label" for="module-order">Orden</label><input class="form-control" id="module-order" name="sort_order" type="number" value="0"></div><div class="col-md-1"><button class="btn btn-primary" type="submit">Añadir</button></div></form></div>
<?php foreach ($modules as $module): ?>
  <section class="admin-card card p-4 mb-4"><div class="d-flex justify-content-between"><div><h2 class="h5 mb-1"><?= e((string) $module['title']) ?></h2><p class="text-muted mb-3"><?= e((string) ($module['summary'] ?? '')) ?></p></div><span class="badge text-bg-light">Orden <?= (int) $module['sort_order'] ?></span></div>
    <form method="post" action="<?= e(url('admin/cursos/' . $courseId . '/modulos/' . (int) $module['id'])) ?>" class="row g-2 mb-3"><?= csrf_field() ?><input type="hidden" name="_method" value="PUT"><div class="col-md-5"><label class="form-label">Editar módulo</label><input class="form-control" name="title" value="<?= e((string) $module['title']) ?>" required></div><div class="col-md-4"><label class="form-label">Resumen</label><input class="form-control" name="summary" value="<?= e((string) ($module['summary'] ?? '')) ?>"></div><div class="col-md-2"><label class="form-label">Orden</label><input class="form-control" name="sort_order" type="number" value="<?= (int) $module['sort_order'] ?>"></div><div class="col-md-1 d-flex align-items-end"><button class="btn btn-outline-primary" type="submit">Guardar</button></div></form>
    <form method="post" action="<?= e(url('admin/cursos/' . $courseId . '/modulos/' . (int) $module['id'])) ?>" class="mb-3"><?= csrf_field() ?><input type="hidden" name="_method" value="DELETE"><button class="btn btn-sm btn-outline-danger" type="submit" onclick="return confirm('El módulo y sus lecciones saldrán del temario y del curso público. Se conservan 30 días por si necesitas recuperarlo. ¿Continuar?');">Enviar módulo a papelera</button></form>
    <ul class="list-group mb-3"><?php foreach ($module['lessons'] as $lesson): ?><li class="list-group-item"><form method="post" action="<?= e(url('admin/cursos/' . $courseId . '/modulos/' . (int) $module['id'] . '/lecciones/' . (int) $lesson['id'])) ?>" class="row g-2 align-items-end"><?= csrf_field() ?><input type="hidden" name="_method" value="PUT"><div class="col-md-4"><label class="form-label">Lección</label><input class="form-control" name="title" value="<?= e((string) $lesson['title']) ?>" required></div><div class="col-md-2"><label class="form-label">Tipo</label><select class="form-select" name="content_type"><?php foreach (['video' => 'Video', 'document' => 'Documento', 'text' => 'Texto', 'link' => 'Enlace'] as $type => $label): ?><option value="<?= e($type) ?>" <?= $lesson['content_type'] === $type ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Duración</label><input class="form-control" name="duration_minutes" type="number" value="<?= $lesson['duration_minutes'] === null ? '' : (int) $lesson['duration_minutes'] ?>"></div><div class="col-md-2"><label class="form-label">Orden</label><input class="form-control" name="sort_order" type="number" value="<?= (int) $lesson['sort_order'] ?>"></div><div class="col-md-1"><label class="form-label">Muestra</label><input class="form-check-input d-block" name="is_preview" value="1" type="checkbox" <?= (int) $lesson['is_preview'] === 1 ? 'checked' : '' ?>></div><div class="col-md-1"><button class="btn btn-outline-primary" type="submit">Guardar</button></div></form><form method="post" action="<?= e(url('admin/cursos/' . $courseId . '/modulos/' . (int) $module['id'] . '/lecciones/' . (int) $lesson['id'])) ?>" class="mt-2"><?= csrf_field() ?><input type="hidden" name="_method" value="DELETE"><button class="btn btn-sm btn-outline-danger" type="submit" onclick="return confirm('La lección dejará de estar disponible para el estudiante. Se conserva 30 días por si necesitas recuperarla. ¿Continuar?');">Enviar a papelera</button></form></li><?php endforeach; ?><?php if ($module['lessons'] === []): ?><li class="list-group-item text-muted">Todavía no hay lecciones.</li><?php endif; ?></ul>
    <form method="post" action="<?= e(url('admin/cursos/' . $courseId . '/modulos/' . (int) $module['id'] . '/lecciones')) ?>" class="row g-2 align-items-end"><?= csrf_field() ?><div class="col-md-4"><label class="form-label">Nueva lección</label><input class="form-control" name="title" required></div><div class="col-md-3"><label class="form-label">Tipo</label><select class="form-select" name="content_type"><option value="video">Video</option><option value="document">Documento</option><option value="text">Texto</option><option value="link">Enlace</option></select></div><div class="col-md-2"><label class="form-label">Duración</label><input class="form-control" name="duration_minutes" type="number"></div><div class="col-md-2"><label class="form-label">Orden</label><input class="form-control" name="sort_order" type="number" value="0"></div><div class="col-md-1"><label class="form-label">Muestra</label><input class="form-check-input d-block" name="is_preview" value="1" type="checkbox"></div><div class="col-12"><button class="btn btn-outline-primary" type="submit">Añadir lección</button></div></form>
  </section>
<?php endforeach; ?>